import dynamic from "next/dynamic";

export const solutionsMap: Record<string, any> = {
  '2': dynamic(() => import('@/components/solutions/Solutions2')),
  '10': dynamic(() => import('@/components/solutions/Solutions10')),
  '49': dynamic(() => import('@/components/solutions/Solutions49')),
  '34': dynamic(() => import('@/components/solutions/Solutions34')),
  '30': dynamic(() => import('@/components/solutions/Solutions30')),
  '13': dynamic(() => import('@/components/solutions/Solutions13')),
  '12': dynamic(() => import('@/components/solutions/Solutions12')),
  '11': dynamic(() => import('@/components/solutions/Solutions11')),
  '41': dynamic(() => import('@/components/solutions/Solutions41')),
  '43': dynamic(() => import('@/components/solutions/Solutions43')),
  '27': dynamic(() => import('@/components/solutions/Solutions27')),
  '7': dynamic(() => import('@/components/solutions/Solutions7')),
  '50': dynamic(() => import('@/components/solutions/Solutions50')),
  '4': dynamic(() => import('@/components/solutions/Solutions4')),
  '39': dynamic(() => import('@/components/solutions/Solutions39')),
  '20': dynamic(() => import('@/components/solutions/Solutions20')),
  '5': dynamic(() => import('@/components/solutions/Solutions5')),
  '1': dynamic(() => import('@/components/solutions/Solutions1')),
  '29': dynamic(() => import('@/components/solutions/Solutions29')),
  '37': dynamic(() => import('@/components/solutions/Solutions37')),
  '44': dynamic(() => import('@/components/solutions/Solutions44')),
  '25': dynamic(() => import('@/components/solutions/Solutions25')),
  '32': dynamic(() => import('@/components/solutions/Solutions32')),
  '47': dynamic(() => import('@/components/solutions/Solutions47')),
  '17': dynamic(() => import('@/components/solutions/Solutions17')),
  '33': dynamic(() => import('@/components/solutions/Solutions33')),
  '15': dynamic(() => import('@/components/solutions/Solutions15')),
  '52': dynamic(() => import('@/components/solutions/Solutions52')),
  '38': dynamic(() => import('@/components/solutions/Solutions38')),
  '66': dynamic(() => import('@/components/solutions/Solutions66')),
  '75': dynamic(() => import('@/components/solutions/Solutions75')),
};
